config/routes.rb
CalendarApp::Application.routes.draw do
  resource :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  
  resources :events

  root 'events#index'

end

app/models/event.rb
class Event
#FOR PAPERCLIP
include Mongoid::Document


include Mongoid::Paperclip

has_mongoid_attached_file :picture

validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/


  field :date, type: Date
  field :input, type: String
  field :location, type: String
  field :address1, type: String
  field :city, type: String
  field :state, type: String
  field :zipcode, type: String
  field :event_type, type: String
  belongs_to :user
  #validates_presence_of :date, :input, :year, :price, :transmission
  #validates_length_of :year, minimum: 4, maximum: 4
  #validates_numericality_of :year, :price,greater_than_or_equal_to: 1950, message: "year must be between 1950 and 2015"
  #validates_inclusion_of :event_type, in: ["Night Event", "Day Event"],
  #message: "not correct transmission"

end

app/models/user.rb
require "bcrypt"
class User
  include Mongoid::Document
  field :name, type: String
  field :email, type: String
  field :password_digest, type: String
  
  #field :is_admin, type: Boolean, default: false
  validates_presence_of :name, :email, :password_digest
  has_many :events 

  def password
    @password
  end

  def password=(new_password)
    @password = new_password
    self.password_digest = BCrypt::Password.create(new_password)
  end

  def authenticate(test_password)
    if BCrypt::Password.new(self.password_digest) == test_password
      self
    else
      false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	# set this if you havent already
    @current_user ||= session[:remember_token] && User.find(session[:remember_token])
  end

  def authenticate_user
    if !current_user
    	flash[:danger] = "You must sign in"
      redirect_to new_sessions_path
    end
  end

  def sign_out
  	session.delete(:remember_token)
  	@current_user= nil
  end

  def sign_in(user)
  	session[:remember_token] =user.id 
  	@current_user = user
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

   before_action :authenticate_user

  def index
    if params[:show] == "all_users_events"
      @events= Event.all
    elsif params[:future] == "true"
      @events=Event.where(:user_id => current_user.id, :date.gte => Date.today)
  	 #@events= current_user.events.all
    else
    @events=Event.where(:user_id => current_user.id, :date.lt => Date.today)  
    end
  end

  def new
  	@event= current_user.events.new
  end

  def create
    @event= Event.new(params.require(:event).permit(:date, :input, :location, :address1, :city, :state, :zipcode, :event_type, :picture))
    #raise @event.inspect
    @event.user = current_user
    if @event.save
      flash[:success]= "Event successfully created"
      redirect_to events_path
    else
      flash[:error]= "Event not yet create! Try Again!"
      render 'new'
    end
  end

  def edit
   
    @event = Event.find(params[:id])
   
  end

  def show
    @event = Event.find(params[:id])

    #@upcoming_event= Event.where("(?)",date) 
    # @user = @current_user
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(params.require(:event).permit(:date, :input, :location, :address1, :city, :state, :zipcode, :event_type, :picture))
      redirect_to event_path
    else
      render 'edit'
    end
  end
 
 def destroy
    @event= Event.find(params[:id])
    #remove the events that would otherwise still exist in the database
    Event.where(event_id: @event.id).destroy_all
    #remove/take out from the burrito from the view
    @event.destroy
    redirect_to events_path
  end

  def event_params
    params.require(:event).permit(:name, :picture)
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.where(:email => params[:session][:email]).first

    if @user == nil || !@user.authenticate(params[:session][:password])
      flash[:error] = "Invalid email/password combination"
      render 'new'
    else
      session[:remember_token] = @user.id
      @current_user = @user

      redirect_to :root
    end

  end

  def destroy
    session.delete(:remember_token)
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "You have signed up successfully"
      redirect_to :root
    else
      render :new
    end
  end

  protected

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>

<%#= form_for @burrito, :html => {:multipart => true} do |f| %>
<%#= f.file_field :picture %>

	Date: <%= f.date_field :date, class: 'date-control' %><br><br>
	Event: <%= f.text_field :input %><br><br>

	Location: <%= f.text_field :location%><br>

	Address:<br> <%= f.text_field :address1, placeholder: "address line 1" %><br>
	<%= f.text_field :city, placeholder: "City" %><br>
	<%= f.select :state,[['Select One'],['AK'],['AL'],['AR'],['AZ'],['CA'],['CO'],['CT'],['DE'],['FL'],['GA'],['HI'],['IA'],['ID'],['IL'],['IN'],['KS'],['KY'],['LA'],['MA'],['MD'],['ME'],['MI'],['MN'],['MO'],['MS'],['MT'],['NC'],['ND'],['NE'],['NH'],['NJ'],['NM'],['NV'],['NY'],['OH'],['OK'],['OR'],['PA'],['RI'],['SC'],['SD'],['TN'],['TX'],['UT'],['VA'],['VT'],['WA'],['WI'],['WV'],['WY']] %><br>
	<%= f.text_field :zipcode, placeholder: "zip code" %><br>


	<%= f.select :event_type, [['Select One'],['Day Event'],['Night Event']]%><br>
	<%= f.file_field :picture %>

	<%= f.submit %><br>
	<div class="back-btn">
		<%= button_to "Go Back ", events_path %>
  <%#= link_to 'Go Back', events_path, class: 'btn btn-default btn-lg' %>
  <div>  
<% end %>

app/views/events/edit.html.erb
<p>Make Changes</p>


<%= render partial: "form" %>

app/views/events/index.html.erb
<h1>All My Events</h1>


<% @events.each do |b| %>
  <ul>
    <li>
     
        
        <div><strong>Date</strong><br><%= b.date %></div>
        <div><strong>Input</strong><br><%= b.input %></div>
        <div><strong>Location</strong><br><%= b.location %></div>
        <div><strong>Address</strong><br><%= b.address1%></div>
        <div><br><%= b.city%></div>
        <div><br><%= b.state%></div>
        <div><br><%= b.zipcode%></div>
        <div><strong>Event Type</strong><br><%= b.event_type %></div></br>
        
       <ul><%= link_to "View", event_path(b) %></ul>
      
        
         
    </li>
  </ul>
<% end %>
  <script type="text/javascript">
//  document.getElementById("currentevent").onclick= function(){
	
// }
</script>

app/views/events/new.html.erb
<%= render partial: 'form' %>

app/views/events/show.html.erb
<h1>YOUR EVENT</h1>
	<%= @event.date %><br>
	<%= @event.input %><br>
	<%= @event.location%><br>
	<%= @event.address1%><br>
	<%= @event.city%><br>
	<%= @event.state%><br>
	<%= @event.zipcode%><br>
	<%= @event.event_type%><br>
	<%= image_tag @event.picture.url %>


<% if (@event.user.id == @current_user.id) %>
	<ul id="currentevent"><%= link_to "Edit your event", edit_event_path(edit: "my_events") %>
 	
	<%= button_to "Delete", {:action => 'destroy', :id => @event.id }, {:method => :delete, confirm: "Are you sure you want to delete this event"} %></ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CalenderApp</title>
  <%= stylesheet_link_tag    "application", params[:controller] %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <% if !@current_user %>
      <a class="navbar-brand" href="#">EVENTS</a>
      <% else %>
      <a class="navbar-brand" href="#"> <%= @current_user.name %></a>
      <% end %>
     
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
       
        <li id="currentevents"><%= link_to "View My Upcomings Events", events_path(future: true) %></li>
      
        <li><%= link_to "View My Past Events", events_path(future: false) %></li>
       
   
        <li><%= link_to "New Event", new_event_path %></li>
         <li><%= link_to "SHOW OTHER EVENTS",events_path(show: "all_users_events") %></li>


          
      </ul>
      <ul class="nav navbar-nav navbar-right">
          <% if !@current_user %>
          <li><%= link_to "Sign Up", new_user_path %></li>
          <li><%= link_to "Sign In", new_sessions_path %></li>
        <% else %>
          <li><%= link_to "Sign Out", sessions_path, :method => :delete %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid">

  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>

  <div class="container">
    <%= yield %>
  </div>

</div>

</body>
</html>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_for @user do |f| %>
  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  
  <%= f.submit %>
<% end %>